name: StadioCraftPlugin
main: me.stadio.Main
version: 1.0

commands:
  regen:
    description: Regen
  fury:
    description: Fury
  rage:
    description: Rage
  tnt:
    description: Throw tnt!
  stadioreload:
    description: reload the config file
  
